### PR TITLE
Remove dimagi envs references (it's on confluence now)

### PR DESCRIPTION
**Pull request by Charl1996**
[Ticket](https://dimagi-dev.atlassian.net/browse/SC-1991).

This PR is just to remove the dimagi-specific content from the public facing docs (it is now on [Confluence](https://confluence.dimagi.com/pages/viewpage.action?spaceKey=GS&title=CommCare+Sync+Ansible)).

### CODE REVIEW

**Comment by czue** [comment]
I'm curious to hear about the motivation for this change. If the goal is to make this repository a truly non-Dimagi-specific public offering, then should we also not remove the submodule itself and come up with a different mechanism for how to manage inventories?

**Comment by czue** [comment]
Hmm, why is that the goal? It feels a bit like "checking a box" without really thinking about whether it's the right box to check.

**Comment by czue** [comment]
Note: I'm not attempting to block merge on this over this point, I just want to make sure we are making reasonable decisions for the product and the community.

**Comment by Charl1996** [comment]
@czue Thanks for sharing your thoughts. 
> Hmm, why is that the goal?

To be honest I'm struggling to figure out why you have that question? Why wouldn't we want to move documentation that is only really dimagi-specific from the public-facing docs, since it's irrelevant to other users?

**Comment by czue** [comment]
My position is that it seems natural for the visibility of the documentation to match the visibility of the code.

I think we agree that the ideal future state is that the tool is meant for public use and Dimagi uses the public version with a complimentary set of internal tools / documentation.

I think where we may see things differently is what the best path to get there is. My position is that by making the documentation private while not addressing the underlying code, you aren't really solving the public/private problem in a meaningful way. And you may be making it worse by making it more difficult for a new person to figure out what is going on.

Is it your belief that this change improves the situation for the average Dimagi developer who wants to use it? Or the average non-Dimagi developer?

**Comment by czue** [comment]
I wonder if there may be a small, simple thing we can do to actually fix the public/private thing. E.g. remove the submodule reference and come up with a generic mechanism for people to add their inventories, along with an example inventory file or something. And then change the workflow for how Dimagi uses it to match what we recommend for others...

**Comment by Charl1996** [comment]
@czue Oh, I think I see you point now. Thanks for explaining. Mmm...maybe it is worth rethinking this a bit.

**Comment by ctsims** [comment]
The best outcome for work like this is definitely "there are no 'first class and second class' users of the system" and that our team deploys the tooling the same way anyone else does.

However, I think it's still fine to remove privately used mechanisms from the public documentation until we get to that point as long as we are consistent about it. If we do leave the docs in the repos (for clarity and comprehension), I do think it makes much more sense to isolate it somewhere more specific which also explains the context, rather than splitting up "If dimagi do X, if general user do Y" across the docs. In this case I think that would be removing the line in 'production.md' (as is done here), and pushing the private context all into `dimagi.md.`

**Comment by Charl1996** [comment]
@ctsims Are you suggesting that we leave the `dimagi.md` file but just add the private "dimagi context"?

**Comment by ctsims** [comment]
Hi Charl,

Yeah. I would add a short sentence into the Dimagi file that says something like "to optimize over a large number of environments, Dimagi's team currently maintains a streamlined way to manage their current environment configurations through a submodule instead of [Whatever the published process is]..." or something similar. That clarifies the function of the submodule while making it clear that it's a separate feature that isn't within scope for open source users.

**Comment by Charl1996** [comment]
Closing this PR in favour of [this](https://github.com/dimagi/commcare-sync-ansible/pull/29) one.

**Pull request closed without merging**
